controller_list:
  - name: fake_gripper_controller
    joints:
      - Joint_Grip_Servo
    gains:
      Joint_Grip_Servo:
        p: 100
        d: 1
        i: 1
        i_clamp: 1

  - name: fake_arm_controller
    joints:
      - Joint_1
      - Joint_2
      - Joint_3
      - Joint_4
      - Joint_5
      - Joint_6